### ISSUE TITLE
How to modify the refresh rate, it is now 1 second

### ISSUE THREAD

**Issue by Bohan-Song** [Congee/NetSpeedMonitor#5]
How to modify the refresh rate, Thank you so much!

**Comment by Bohan-Song** [comment]
Has anything to do with this?
how i can change ...
static const char *suffixes[] = {
	"bytes",
	"KiB",
	"MiB",
	"GiB",
	"TiB",
	"PiB",
	"EiB",
	"ZiB",
	"YiB"
};

**Comment by Congee** [comment]
change this line and rebuild it https://github.com/Congee/NetSpeedMonitor/blob/1e8d2981b19b0f0e30bcc8e963013e0ad7d07e49/SpeedMonitor/AppDelegate.m#L20
